name 'formatron_postgresql'
version '0.1.1'
description 'Formatron PostrgeSQL cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/postgresql-cookbook'
issues_url 'https://github.com/formatron/postgresql-cookbook/issues'
supports 'ubuntu'
